evewspace/Map/urls.py
#    Eve W-Space
#    Copyright (C) 2013  Andrew Austin and other contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version. An additional term under section
#    7 of the GPL is included in the LICENSE file.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, include, url

sigpatterns = patterns('Map.views',
        url(r'^activate/$', 'activate_signature'),
        url(r'^escalate/$', 'escalate_site'),
        url(r'^clear/$', 'mark_signature_cleared'),
        url(r'^remove/$', 'delete_signature'),
        url(r'^edit/$', 'edit_signature'),
        url(r'^spawns/$', 'site_spawns'),
        url(r'^own/$', 'toggle_sig_owner'),
        )

syspatterns = patterns('Map.views',
        url(r'^$', 'system_details'),
        url(r'^menu/$', 'system_menu'),
        url(r'^interest/$','set_interest'),
        url(r'^location/$', 'manual_location'),
        url(r'^scanned/$', 'mark_scanned'),
        url(r'^remove/$', 'remove_system'),
        url(r'^edit/$', 'edit_system'),
        url(r'^destinations/$', 'destination_list'),
        url(r'^addchild/$', 'manual_add_system'),
        url(r'^signatures/$', 'get_signature_list'),
        url(r'^signatures/new/$', 'edit_signature'),
        url(r'^signatures/purge/$', 'purge_signatures'),
        url(r'^signatures/bulkadd/$', 'bulk_sig_import'),
        url(r'^signatures/(?P<sig_id>\d+)/', include(sigpatterns)),
        url(r'^collapse/$', 'collapse_system'),
        url(r'^resurrect/$', 'resurrect_system'),
        )

wormholepatterns = patterns('Map.views',
        url(r'^edit/$$', 'edit_wormhole'),
        )

mappatterns = patterns('Map.views',
        url(r'^$', 'get_map'),
        url(r'^update/$', 'map_checkin'),
        url(r'^refresh/$', 'map_refresh'),
        url(r'^delete/$', 'delete_map'),
        url(r'^system/new/$', 'add_system'),
        url(r'^system/tooltips/$', 'system_tooltips'),
        url(r'^system/(?P<ms_id>\d+)/', include(syspatterns)),
        url(r'^wormhole/tooltips/$', 'wormhole_tooltips'),
        url(r'^wormhole/(?P<wh_id>\d+)/', include(wormholepatterns)),
        url(r'^settings/$', 'map_settings'),
        )

spawnspatterns = patterns('Map.views',
        url(r'^edit/$', 'edit_spawns'),
        url(r'^delete/$', 'delete_spawns'),
        )

sigtypepatterns = patterns('Map.views',
        url(r'^edit/$', 'edit_sigtype'),
        url(r'^delete/$', 'delete_sigtype'),
        )

settingspatterns = patterns('Map.views',
        url(r'^general/$', 'general_settings'),
        url(r'^sitespawns/$', 'sites_settings'),
        url(r'^permissions/$', 'global_permissions'),
        url(r'^sitespawns/add/$', 'add_spawns'),
        url(r'^sitespawns/(?P<spawn_id>\d+)/', include(spawnspatterns)),
        url(r'^destinations/$', 'destination_settings'),
        url(r'^user-destinations/$', 'destination_settings', {'user': True}),
        url(r'^user-destinations/new/$', 'add_personal_destination'),
        url(r'^destinations/new/$', 'add_destination'),
        url(r'^destinations/(?P<dest_id>\d+)/delete/$', 'delete_destination'),
        url(r'^sigtypes/$', 'sigtype_settings'),
        url(r'^sigtypes/(?P<sigtype_id>\d+)/', include(sigtypepatterns)),
        )

urlpatterns = patterns('Map.views',
        url(r'^new/$', 'create_map'),
        url(r'^(?P<map_id>\d+)/', include(mappatterns)),
        url(r'^settings/', include(settingspatterns)),
        )

evewspace/Map/models.py
#    Eve W-Space
#    Copyright (C) 2013  Andrew Austin and other contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version. An additional term under section
#    7 of the GPL is included in the LICENSE file.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.db import models
from django.contrib.auth.models import User, Group
from core.models import SystemData
from django import forms
from django.forms import ModelForm
from datetime import datetime, timedelta
import pytz
import time
from Map import utils
from Map.utils import MapJSONGenerator
from django.core.cache import cache
# Create your models here.

class WormholeType(models.Model):
    """Stores the permanent information on wormhole types.
    Any changes to this table should be made with caution.

    """
    name = models.CharField(max_length = 4, unique = True)
    maxmass = models.BigIntegerField()
    jumpmass = models.BigIntegerField()
    lifetime = models.IntegerField()
    # source is a  2-char fields that can be:
    # 1-6 : Wormhole classes 1-6
    # H : High Sec Only (e.g. freighter capable K > C5 in high)
    # NH : Low or Nullsec (e.g. cap capable K > C5)
    # K : Any K-space (e.g. X702 to a C3)
    # N: Nullsec
    # L: Lowsec
    # Z: Class 5 or 6 (5/6 > K holes)
    # X: Special ID for K162 and stargates
    source = models.CharField(max_length = 2)
    # Destination is an integer representation of System.sysclass
    # Except that it may be 0 which indicates a K162 or Stargate
    destination = models.IntegerField()
    target = models.CharField(max_length = 15)

    def __unicode__(self):
        """Returns Wormhole ID as unicode representation."""
        return self.name

    def dest_string(self):
        """Returns a readable destination. Cx for w-space and H, L, N otherwise."""
        if self.destination < 7 and self.destination > 0:
            return "C%s" % (self.destination)
        if self.destination == 0:
            return "Varies"
        if self.destination == 7:
            return "High Sec"
        if self.destination == 8:
            return "Low Sec"
        if self.destination == 9:
            return "Null Sec"
        return "Unknown"

class System(SystemData):
    """Stores the permanent record of a solar system.
    This table should not have rows added or removed through Django.

    """
    sysclass_choices = ((1, "C1"), (2, "C2"), (3, "C3"), (4, "C4"), (5, "C5"),
            (6, "C6"), (7, "High Sec"), (8, "Low Sec"), (9, "Null Sec"))
    sysclass = models.IntegerField(choices = sysclass_choices)
    importance_choices = ((0, "Regular"),
                     (1, "Dangerous System"),
                     (2, "Important System"))
    importance = models.IntegerField(choices = importance_choices, default = 0)
    occupied = models.TextField(blank = True)

    occupied = models.TextField(blank = True)
    info = models.TextField(blank = True)
    lastscanned = models.DateTimeField()
    npckills = models.IntegerField(null=True, blank=True)
    podkills = models.IntegerField(null=True, blank=True)
    shipkills = models.IntegerField(null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    first_visited = models.DateTimeField(null=True, blank=True)
    last_visited = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        """Returns name of System as unicode representation"""
        return self.name

    def is_kspace(self):
        return self.sysclass >= 7

    def is_wspace(self):
        return self.sysclass < 7

    def get_spec(self):
        if self.sysclass < 7:
            return self.wsystem
        else:
            return self.ksystem

    def save(self, *args, **kwargs):
        self.updated = datetime.now(pytz.utc)
        if self.lastscanned < datetime.now(pytz.utc) - timedelta(days=3):
            self.lastscanned = datetime.now(pytz.utc)
        if not self.first_visited:
            self.first_visited = datetime.now(pytz.utc)
            self.last_visited = datetime.now(pytz.utc)
        if self.last_visited < datetime.now(pytz.utc) - timedelta(days=2):
            self.last_visited = datetime.now(pytz.utc)

        super(System, self).save(*args, **kwargs)

    def add_active_pilot(self, username, charid, charname,
            shipname, shiptype):
        sys_cache_key = 'sys_%s_locations' % self.pk
        current_time = time.time()
        time_threshold = current_time - (15 * 60)
        sys_location_dict = cache.get(sys_cache_key)
        location = (username, charname, shipname, shiptype, current_time)
        if sys_location_dict:
            sys_location_dict.pop(charid, None)
            sys_location_dict[charid] = location
        else:
            sys_location_dict = {charid: location}

        # Prune dict to prevent carrying over stale entries
        for charid, location in sys_location_dict.items():
            if location[4] < time_threshold:
                sys_location_dict.pop(charid, None)

        cache.set(sys_cache_key, sys_location_dict, 15 * 60)
        return location

    def remove_active_pilot(self, charid):
        current_time = time.time()
        time_threshold = current_time - (15 * 60)
        sys_cache_key = 'sys_%s_locations' % self.pk
        sys_location_dict = cache.get(sys_cache_key)
        if sys_location_dict:
            sys_location_dict.pop(charid, None)
            # Prune dict to prevent carrying over stale entries
            for charid, location in sys_location_dict.items():
                if location[4] < time_threshold:
                    sys_location_dict.pop(charid, None)
            cache.set(sys_cache_key, sys_location_dict, 15 * 60)
        return True

    def _active_pilot_list(self):
        sys_cache_key = 'sys_%s_locations' % self.pk
        sys_location_dict = cache.get(sys_cache_key)
        if sys_location_dict:
            return sys_location_dict
        else:
            return {}

    pilot_list = property(_active_pilot_list)

    def clear_sig_cache(self):
        cache.delete('sys_%s_sig_list' % self.pk)


class KSystem(System):
    sov = models.CharField(max_length = 100)
    jumps = models.IntegerField(blank=True, null=True)

    def jumps_to(self, destination):
        """
        Returns the number of gate jumps to the destination by shortest route.
        """
        return utils.RouteFinder().route_length(self, destination)

    def distance(self, destination):
        """
        Returns the light-year distance to the destination.
        """
        return utils.RouteFinder().ly_distance(self, destination)


class WSystem(System):
    static1 = models.ForeignKey(WormholeType, blank=True, null=True, related_name="primary_statics")
    static2 = models.ForeignKey(WormholeType, blank=True, null=True, related_name="secondary_statics")
    effect = models.CharField(max_length=50, blank=True, null=True)

class Map(models.Model):
    """Stores the maps available in the map tool. root relates to System model."""
    name = models.CharField(max_length = 100, unique = True)
    root = models.ForeignKey(System, related_name="root")
    # Maps with explicitperms = True require an explicit permission entry to access.
    explicitperms = models.BooleanField(default=False)

    class Meta:
        permissions = (("map_unrestricted", "Do not require excplicit access to maps."),
                ("map_admin", "Access map configuration."),)

    def __unicode__(self):
        """Returns name of Map as unicode representation."""
        return self.name

    def __contains__(self, system):
        """
        A convience to allow 'if system in map:' type statements to determine if
        there exist a MapSystem with map == map and system == system.
        NOTE: system must be a System, NOT a MapSystem
        """
        #I *think* this should be handled by the filter used in the main return
        #statement, but as I require this behaviour I'll make it explicit
        if system is None:
            return False

        return self.systems.filter(system=system).exists()

    #Given a __contains__ function I guess it makes sense to implement this
    #so for ... in ... will work too.
    def __iter__(self):
        """
        Returns an iterator over all Systems in the map
        NOTE: returns Systems not MapSystems
        """
        for msys in self.systems.all():
            yield msys.system

    def add_log(self, user, action, visible=False):
        """
        Adds a log entry into a MapLog for the map.
        """
        log = MapLog(user=user, map=self, action=action,
                     timestamp=datetime.now(pytz.utc),
                     visible=visible)
        log.save()

    def get_permission(self, user):
        """
        Returns the highest permision that user has on the map.
        0 = No Access
        1 = Read Access
        2 = Write Access
        """
        #Anonymous users always return 0
        if user.is_anonymous():
            return 0
        #Special case: If user is a map admin, always return 2
        if user.has_perm('Map.map_admin'):
            return 2
        #Special case: if user is unrestricted we don't care unless the map
        #requires explicit permissions
        if user.has_perm('Map.map_unrestricted') and not self.explicitperms:
            return 2

        #Otherwise take the highest of the permissions granted by the groups

evewspace/Map/templates/add_sig_form.html
<div id="sys{{system.pk}}SigAddForm" class="sigAddFormDiv">
    <h6>Add Signature:</h6>    
    <form id="sigAddForm" class="form-inline" action="system/signatures/add" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
            <br /><span class="label label-warning">{{field.errors}}</span> <br />
            {% endif %}
            {{field.label_tag}} {{field}} &nbsp
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="Add Sig" />
    </form>
    <script type="text/javascript">
        $("#sigAddForm").submit(function(e){
                    e.preventDefault();
                    AddSignature({{system.pk}});
                    return false;
                    });
    </script>
</div>

evewspace/Map/templates/add_system_box.html
<div id="addSystemDialog">
    <div class="modal-header">
        <h4>Add System Connected To: {{topMs.system.name}}</h4>
    </div>
    <div class="modal-body">
    <form id="sysAddForm" class="form-horizontal" action="system/new/" method="post">
        {% csrf_token %}
        <input type="hidden" class="sysAddInput" name="topMsID" value="{{topMs.pk}}">
        <div class="control-group">
            <label class="control-label" for="sysNameBox">System:</label>
            <div class="controls">
                <input type="text" class="sysAddInput systemAuto" name="bottomSystem" id="sysNameBox" value ="{{newsystem}}" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="friendlyNameBox">Friendly Name <br /> (Max 8 Char.):</label>
            <div class="controls">
                <input type="text" class="sysAddInput" name="friendlyName" id="friendlyNameBox" value="">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="timeStatusAnchor">Time Status:</label>
            <div class="controls">
                <input type="radio" id="timeStatusAnchor" class="sysAddInput" name="timeStatus" value="0" checked="checked">Normal &nbsp
                <input type="radio" class="sysAddInput" name="timeStatus" value="1">End of Life
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="massStatusAnchor">Mass Status:</label>
            <div class="controls">
                <input type="radio" id="massStatusAnchor" class="sysAddInput" name="massStatus" value="0" checked="checked">Normal &nbsp
                <input type="radio" class="sysAddInput" name="massStatus" value="1">First Shrink &nbsp
                <input type="radio" class="sysAddInput" name="massStatus" value="2">Critical<br />
            </div>
            <br />
            <div>
                <h5>Wormhole Information</h5>
                <div class="row span6">
                    <div class="span2"> 
                        <h5>{{topMs.system.name}} ({{topMs.friendlyname}})</h5>
                        <fieldset style="margin-left: 25px;">
                                <label for="topTypeInput">Type:</label>
                                <input type="text" class="sysAddInput wormholeAuto input-mini" id="topTypeInput" name="topType" value="K162" onclick="this.value = '';" />
                                <label style="margin-top: 5px;" class="checkbox" for="topBubbledCheckbox">
                                    <input type="checkbox" class="sysAddInput" name="topBubbled" id="topBubbledCheckbox">Bubbled
                                </label>
                        </fieldset>
                    </div>
                    <div class="span1">
                        <h5><-------></h5>
                    </div>
            <div class="span2">
                <h5>Other Side</h5>
                <fieldset style="margin-left: 35px;">
                    <label for="bottomTypeInput">Type:</label>
                    <input type="text" class="sysAddInput wormholeAuto input-mini" id="bottomTypeInput" name="bottomType" value="K162" onclick="this.value = '';" />
                    <label style="margin-top: 5px;" class="checkbox" for="bottomBubbledCheckbox">
                        <input type="checkbox" id="bottomBubbledCheckbox" class="sysAddInput" name="bottomBubbled">Bubbled
                    </label>
                </fieldset>
            </div>
    </div>
        </div>

            <input type="submit" style="display: none;">
        </form>
    </div>
</div>
    <div class="modal-footer">
        <a href="#" id="sysCloseButton" class="btn" data-dismiss="modal">Close</a>
            <a href="#" id="sysAddSubmit" onclick="$('#sysAddForm').submit();" class="btn btn-primary">Add System</a>
    </div>
        <script type="text/javascript">
           $('#sysAddForm').submit(function(e){
                        e.preventDefault();
                        AddSystem();
                        $('#modalHolder').modal('hide');
                        return false;
            });
        </script>
    </div>

evewspace/Map/templates/edit_sig_form.html
<div id="sys{{system.pk}}SigAddForm" class="sigAddFormDiv">
    <h6>Edit Signature:</h6>
    <form id="sigEditForm" class="form-inline" action="system/signatures/add" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
            <br /><span class="label label-warning">{{field.errors}}</span> <br />
            {% endif %}
            {{field.label_tag}} {{field}} &nbsp
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="Save Sig" />
    </form>
    <script type="text/javascript">
        $("#sigEditForm").submit(function(e){
                    e.preventDefault();
                    EditSignature({{system.pk}}, {{sig.pk}});
                    return false;
                });
    </script>
</div>

evewspace/Map/templates/edit_system.html
<div id="editSystemDialog">
    <div class="modal-header">
        <h4>Edit System: {{mapsys.system.name}}({{mapsys.friendlyname}})</h4>
    </div>
    <div class="modal-body">
    <form id="editSystemForm" class="editSystemForm" method="post" action="system/{{mapsys.pk}}/edit/">
        {% csrf_token %}
        <h4>Friendly Name:</h4> 
        <input type="text" id="friendlyField" name="friendlyName" value="{{mapsys.friendlyname}}">
        <h4>Info: </h4>
        <textarea name="info" style="color: #000000;" id="infoField" rows=8 cols=50>{{info}}</textarea> 
        <h4>Occupied: </h4>
        <textarea name="occupied" style="color: #000000;" id="occupiedField" rows=8 cols=50 >{{occupied}}</textarea><br />
        Type: &nbsp
        <input type="radio" class="editWormholeInput" name="importance" value="0" {% if mapsys.system.importance == 0 %} checked="checked" {% endif %}> Regular System&nbsp
        <input type="radio" class="editWormholeInput" name="importance" value="1" {% if mapsys.system.importance == 1 %} checked="checked" {% endif %}> Dangerous System &nbsp
        <input type="radio" class="editWormholeInput" name="importance" value="2" {% if mapsys.system.importance == 2 %} checked="checked" {% endif %}> Important System
        <br />
        <input type="submit" style="display: none;">
    </form>
</div>
<div class="modal-footer">
    <a href="#" class="btn" id="btnClose">Cancel</a>
    <a href="#" class="btn btn-primary" id="btnEditSys">Edit Info</a>
</div>
    <script type="text/javascript">
        $('#editSystemForm').submit(function(e){
            e.preventDefault();
            EditSystem({{mapsys.pk}}, {{mapsys.system.pk}});
            $('#modalHolder').modal('hide');
            return false;
            });
        $('#btnEditSys').click(function(e){
                EditSystem({{mapsys.pk}}, {{mapsys.system.pk}});
            $('#modalHolder').modal('hide');
            });
        $('#btnClose').click(function(e){
            $('#modalHolder').modal('hide');
            });
    </script>
</div>

evewspace/Map/templates/log_div.html
{% if logs %}
<ul id="logList" class="logList">
    {% for log in logs %}
    <li class="logEntry">
    	<strong>User: {{ log.user.username }}</strong>
    	<strong>Action: {{ log.action }}</strong>
    </li>
    {% endfor %}
</ul>
{% endif %}

evewspace/Map/templates/map.html
{% extends "base.html" %}
{% block title %}Map: {{map.name}}{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{{STATIC_URL}}js/raphael-min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/map_functions.js"></script>
    <link rel="stylesheet" href="{{STATIC_URL}}css/map.css" type="text/css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/map-slate.css" type="text/css" />
    {% if is_igb %}
    <script type="text/javascript">var is_igb = true;</script>
    {% else %}
    <script type="text/javascript">var is_igb = false;</script>
    {% endif %}
    <script type="text/javascript">var ajax_image = "<img src= '{{STATIC_URL}}images/loading.gif'></img>"; </script>
{% endblock %}
{% block contentheader %}
<div class="btn-toolbar">
    <button class='btn btn-mini' onclick="RefreshMap();"><i class="icon-refresh"></i> Refresh</button>
    <button id="btnRefreshToggle" class="btn btn-mini btn-info" onclick="ToggleAutoRefresh();">Auto Refresh: ON</button>
    {% if is_igb %}
    <button id="btnSilentAdd" class="btn btn-mini btn-info" onclick="ToggleSilentAdd();">Silent IGB Mapping: OFF</button>
    {% endif %}
</div>
<div id="mapDiv" class="mapDiv">
</div>
<div id="systemTooltipHolder">
</div>
<div id="legendDiv">
    <p class="text-info">
        <em>Legend:</em> &nbsp
        <ul class="inline">
            <li><img src='{{STATIC_URL}}images/pvp.png' height='32' width='32'></img>  PVP Activity </li>
            <li> <img src='{{STATIC_URL}}images/carebears.png' height='32' width='32'></img>  NPC Kills </li>
            <li> <img src='{{STATIC_URL}}images/mylocation.png' height='32' width='32'></img>  You are here! </li>
        {% if perms.SiteTracker.can_sitetracker %}
        <li><img src='{{STATIC_URL}}images/farm.png' height='32' width='32'></img>  SiteTracker Up! </li>
        {% endif %}
    </p>
</div>
<div id="logDiv" class="logDiv">
</div>
<div id="wormholeTooltipHolder" style="">
</div>
{% endblock %}
{% block content %}
<div id="sysInfoDiv" class="sysInfoDiv">
    <a name="sysInfo"></a>
</div>
{% endblock %}

evewspace/Map/templates/map_admin.html
    {% load mapconfig %}
{% map_global_admin %}

evewspace/Map/templates/map_list.html
{% for map in maps %}
<li><a href="{% url 'Map.views.get_map' map.pk %}">{{map.name}}</a></li>
{% endfor %}

evewspace/Map/templates/map_settings.html
<div class="accordion" id="map_accordion">
    {% load static %}
    {% load mapconfig %}
    <script type="text/javascript" src="{% get_static_prefix %}js/map_settings.js"></script>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#map_accordion" href="#mapGeneral">
                General Settings
            </a>
        </div>
        <div id="mapGeneral" class="accordion-body collapse">
            <div class="accordion-inner">
                <p class="text-info">
                    These settings affect the behavior of all maps.
                </p>
                <div id="generalDiv">
                </div>
            </div>
        </div>
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#map_accordion" href="#Destinations">
                Global Destinations
            </a>
        </div>
        <div id="Destinations" class="accordion-body collapse">
            <div class="accordion-inner">
                <p class="text-info">
                    The distance to these systems (jumps and LY) appear in the details for all K-Space systems.
                </p>
                <div id="destinationsDiv">
                </div>
            </div>
        </div>
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#map_accordion" href="#Permissions">
                Global Permissions
            </a>
        </div>
        <div id="Permissions" class="accordion-body collapse">
            <div class="accordion-inner">
                <p class="text-info">
                    These permissions affect access across all maps.
                </p>
                <div id="globalPermsDiv">
                </div>
            </div>
        </div>
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#map_accordion" href="#SigTypes">
                Signature Types
            </a>
        </div>
        <div id="SigTypes" class="accordion-body collapse">
            <div class="accordion-inner">
                <p class="text-info">
                Here you can define custom signature types. <br />
                <br />
                NOTE: Deleting a Signature Type will remove all signatures of that type and all site spawns associated with that type.
                </p>
                <div id="sigTypesDiv">
                </div>
            </div>
        </div>
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#map_accordion" href="#SiteSpawns">
                Site Spawns
            </a>
        </div>
        <div id="SiteSpawns" class="accordion-body collapse">
            <div class="accordion-inner">
                <p class="text-info">
                    Here you can add, remove, and change site listings.
                </p>
                <div id="siteSpawnsDiv">
                </div>
            </div>
        </div>
        {% for m in maps %}
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#map_accordion" href="#map{{m.pk}}Settings">
                Map: {{m.name}}
            </a>
        </div>
        <div id="map{{m.pk}}Settings" class="accordion-body collapse">
            <div class="accordion-inner">
                <div id="map{{m.pk}}Div">
                    {% map_settings m %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>    
</div>

evewspace/Map/templates/new_map.html
{% extends "base.html" %}
{% block title %}Eve W-Space: New Map{% endblock %}
{% block content %}
<form action="{% url 'Map.views.create_map' %}" method="post">
    {% csrf_token %}
    {{form.non_field_errors}}
    <table>
        {{form.name_errors}}
        <tr>
            <td><label for="id_name">Map Name:</label></td>
            <td><input type="text" id="id_name" name="name" /></td>
        </tr>
        {{form.root_errors}}
        <tr>
            <td><label for="id_root">Root System:</label></td>
            <td><input type="text" id="id_root" name="root" class="systemAuto" /></td>
        </tr>
        {{form.explicitperms_errors}}
        {% if perms.Map.map_admin %}
        <tr>
            <td><label for="id_explicitperms">Require Explicit Permissions:</label> </td>
            <td><input type="checkbox" id="id_explicitperms" name="explicitperms" /></td>
        </tr>
        {% endif %}
    </table>
    <input class="btn btn-primary" type="submit" value="Submit" />
</form>
{% endblock %}

evewspace/Map/templates/system_destinations.html
<table class="destinationTable">
    <tr>
        <th>System</th>
        <th>Jumps</th>
        <th>LY</th>
        {% if is_igb_trusted %}
        <th>Autopilot</th>
        {% endif %}
    </tr>
    {% for dest, jumps, ly in destinations %}
        <tr>
            <td>{{dest.name}}</td>
            <td>{{jumps}}</td>
            <td>{{ly}}</td>
            {% if is_igb_trusted %}
            <td><button class='btn btn-mini btn-info' onclick="CCPEVE.setDestination({{dest.pk}});">D</button>&nbsp<button class='btn btn-mini btn-info' onclick="CCPEVE.addWaypoint({{dest.pk}});">W</button></td>
            {% endif %}
        </tr>
    {% endfor %}
</table>