evewspace/POS/urls.py
#    Eve W-Space
#    Copyright (C) 2013  Andrew Austin and other contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version. An additional term under section
#    7 of the GPL is included in the LICENSE file.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, include, url

pospatterns = patterns('POS.views',
        url(r'remove/$', 'remove_pos'),
        url(r'edit/$', 'edit_pos'),
        )

syspatterns = patterns('POS.views',
        url(r'(?P<posID>\d+)/', include(pospatterns)),
        url(r'add/$', 'add_pos'),
        url(r'$', 'get_pos_list'),
        )

urlpatterns = patterns('POS.views',
        url(r'(?P<sysID>\d+)/', include(syspatterns)),
        )

evewspace/POS/models.py
#    Eve W-Space
#    Copyright (C) 2013  Andrew Austin and other contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version. An additional term under section
#    7 of the GPL is included in the LICENSE file.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.db import models
from core.models import Type, Location
from API.models import CorpAPIKey
from core.models import Corporation, Alliance
from Map.models import System
import csv
from django.contrib.auth.models import User
import pytz


class POS(models.Model):
    """Represents a POS somewhere in space."""
    system = models.ForeignKey(System, related_name="poses")
    planet = models.IntegerField()
    moon   = models.IntegerField()
    towertype = models.ForeignKey(Type, related_name="inspace")
    corporation = models.ForeignKey(Corporation, related_name="poses")
    posname = models.CharField(max_length=100, blank=True, null=True)
    fitting = models.TextField(blank=True, null=True)
    #Using CCP's status codes here for sanity with API checks
    status = models.IntegerField(choices = ((0, 'Unanchored'), (1, 'Anchored'),
        (2, 'Onlining'), (3, 'Reinforced'), (4, 'Online')))

    #This should be the time the tower exits RF
    #TODO: add a validator to make sure this is only set if status = 3 (Reinforced)
    rftime = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField()
    # These values will be set by the TSV parser from d-scan data if available
    guns = models.IntegerField(null=True, blank=True)
    ewar = models.IntegerField(null=True, blank=True)
    sma = models.IntegerField(null=True, blank=True)
    hardener = models.IntegerField(null=True, blank=True)
    # This is a short comment that is displayed as a warning
    warpin_notice = models.CharField(blank=True, null=True, max_length=64)

    class Meta:
        ordering = ['system__name', 'planet', 'moon']

    def clean(self):
        from django.core.exceptions import ValidationError
        if self.rftime and self.status != 3:
            raise ValidationError("A POS cannot have an rftime unless it is reinforced")

    def __unicode__(self):
        return self.posname

    #overide save to implement posname defaulting to towertype.name
    def save(self, *args, **kwargs):
        if not self.posname:
            self.posname = self.towertype.name
        # Mark tower as having been updated
        from datetime import datetime
        import pytz
        self.updated = datetime.now(pytz.utc)
        super(POS, self).save(*args, **kwargs)

    def size(self):
        """
        Returns the size of the tower, Small Medium or Large.
        """
        if u'Small' in self.towertype.name:
            return u'Small'
        if u'Medium' in self.towertype.name:
            return u'Medium'

        return u'Large'

    def fit_from_dscan(self, dscan):
        """
        Fills in a POS's fitting from a copy / paste of d-scan results.
        """
        return self.fit_from_iterable(csv.reader(dscan.splitlines(), delimiter="\t"))

    def fit_from_iterable(self, fit):
        """
        Fills in a POS's fitting from an iterable (normally parsed d-scan)
        """
        from core.models import Type
        itemDict={}
        # marketGroupIDs to consider guns, ewar, hardeners, and smas
        gunsGroups = [480, 479, 594, 595, 596]
        ewarGroups = [481, 1009]
        smaGroups = [484,]
        hardenerGroups = [485,]
        towers = 0
        self.sma = 0
        self.hardener = 0
        self.guns = 0
        self.ewar = 0
        for row in fit:
            try:
                itemType = Type.objects.get(name=row[1])
            except Type.DoesNotExist: #odd bug where invalid items get into dscan
                continue
            if itemType.marketgroup:
                groupTree = []
                parent = itemType.marketgroup
                while parent:
                    groupTree.append(parent.id)
                    parent = parent.parentgroup
                if itemType.marketgroup.id in gunsGroups:
                    self.guns += 1
                if itemType.marketgroup.id in ewarGroups:
                    self.ewar += 1
                if itemType.marketgroup.id in smaGroups:
                    self.sma += 1
                if itemType.marketgroup.id in hardenerGroups:
                    self.hardener += 1
                if itemType.marketgroup.id == 478:
                    towers += 1
                    towertype = itemType
                    posname = row[0]
                if itemDict.has_key(itemType.name):
                    itemDict[itemType.name] += 1
                elif 1285 in groupTree and 478 not in groupTree:
                    itemDict.update({itemType.name: 1})

        self.fitting = "Imported from D-Scan:\n"
        for itemtype in itemDict:
            self.fitting += "\n%s : %s" % (itemtype, itemDict[itemtype])
        if towers == 1 and self.towertype_id is None and self.posname is None:
            self.towertype = towertype
            self.posname = posname
        if towers == 0 and self.towertype_id is None:
            raise AttributeError('No POS in the D-Scan!')
        elif towers <= 1:
            self.save()
        else:
            raise AttributeError('Too many towers detected in the D-Scan!')

class CorpPOS(POS):
    """A corp-controlled POS with manager and password data."""
    manager = models.ForeignKey(User, null=True, blank=True, related_name='poses')
    password = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    #Let's store the CCP Item ID for the tower here to make API lookup easier
    #If it is null, then we are not tracking this POS via API
    apiitemid = models.BigIntegerField(null=True, blank=True)
    apikey = models.ForeignKey(CorpAPIKey, null=True, blank=True, related_name='poses')

    class Meta:
        permissions = (('can_see_pos_pw', 'Can see corp POS passwords.'),
        ('can_see_all_pos', 'Sees all corp POSes regardless of manager.'),)


class POSApplication(models.Model):
    """Represents an application for a personal POS."""
    applicant = models.ForeignKey(User, null=True, blank=True, related_name='posapps')
    towertype = models.ForeignKey(Type, null=True, blank=True, related_name='posapps')
    residents = models.ManyToManyField(User)
    normalfit = models.TextField()
    siegefit = models.TextField()
    #Once it is approved, we will fill in these two to tie the records together
    approved = models.DateTimeField(blank=True, null=True)
    posrecord = models.ForeignKey(CorpPOS, blank=True, null=True, related_name='application')

    class Meta:
        permissions = (('can_close_pos_app', 'Can dispose of corp POS applications.'),)

    def __unicode__(self):
        return 'Applicant: %s  Tower: %s' % (self.applicant.username, self.towertype.name)


class POSVote(models.Model):
    """Represents a vote on a personal POS application."""
    application = models.ForeignKey(POSApplication, related_name='votes')
    voter = models.ForeignKey(User, related_name='posvotes')
    vote = models.IntegerField(choices=((0,'Deny'), (1, 'Approve'), (2, 'Abstain')))

evewspace/POS/templates/add_pos.html
<div title="Add Starbase" id="addPOSDialog" class="addPOSDialog">
    <div class="modal-header">
        <div class="row">
            <div class="span6">
                <h4>Add POS: {{system.name}}</h4>
            </div>
            <div class="span3 offset2">
                <a href="#" class="btn" onclick="$('#modalHolder').modal('hide');">Cancel</a>
                <a href="#" class="btn btn-info" id="btnAddPOS">Add POS</a>
            </div>
        </div>
         <ul class="nav nav-pills" style="margin-bottom:0">
            <li class="active"><a id="auto" href="#" data-toggle="tab">Auto</a></li>
            <li><a href="#" data-toggle="tab" id="manual">Manual</a></li>
          </ul>
    </div>
    <div class="modal-body">
        <div class="alert alert-error" id="pos_message" style="display: none;">
            <p id="pos_error"></p>
        </div>
      <form id="addPOSForm" action="/pos/{{system.pk}}/add" method="POST">
        {% csrf_token %}
        <input id="auto-field" name="auto" value="1" type="hidden">
        Full Corp Name: <input id="corpBox" class="corpAuto" name="corp" type="text" > <br />
        <div class="manual-fields">
          <span class="label label-warning" id="digiterror">Please enter digits only for planet and moon. </span><br /><br />
          Planet: <input name="planet" class="input-mini" type="text"> 
          Moon: <input name="moon" class="input-mini" type="text"> <br />
          Tower Name: <input name="name" type="text"> <br />
          Tower Type: <input id="towertype" class="towerAuto" name="tower" type="text"> <br />
        </div>
        Status: <br /><input type="radio" onclick="Test(this);" name="status" value="0">&nbsp; Unanchored
        <br /><input type="radio" name="status" onclick="Test(this);" value="1">&nbsp; Anchored
        <br /><input type="radio" name="status" onclick="Test(this);" value="2">&nbsp; Onlining
        <br /><input type="radio" name="status" onclick="Test(this);" value="3"> &nbsp; Reinforced
        <br /><input type="radio" name="status" value="4" onclick="Test(this);" checked="checked"> &nbsp Online
        <br />
        <div id="rftime" class="rftimerdiv" style="display: none">
            RF Timer:<br /> D: <input name="rfdays" class="input-mini" type="text">
            H: <input name="rfhours" class="input-mini" type="text">
            M: <input name="rfminutes" class="input-mini" type="text">
        </div>
        <br />Fitting: <br />
        <p id="auto-help">Paste a 360° dscan (irrelevant range) with Active Overview Settings unticked, from ongrid with the POS</p>
        <p id="manual-help">Paste a dscan showing POS modules from just this POS<p>
        <textarea cols=40 rows=10 name="fitting"></textarea><br />
        <div class="manual-fields">
          Parse as D-Scan Paste: <input type="checkbox" name="dscan" value="1"> <br />
        </div>
      </form>
  </div>
</div>
    <div class="modal-footer">
    </div>
    <script type="text/javascript">
    function Test(rad){
        var rads=document.getElementsByName(rad.name);
        document.getElementById('rftime').style.display=(rads[3].checked)?'block':'none';
    }
    $('#addPOSForm').submit(function(e){
                e.preventDefault();
                AddPOS({{system.pk}});
                });
    $('#btnAddPOS').click(function(e){
                AddPOS({{system.pk}});
                });
    $('#auto').click(function(e){
        $('.manual-fields, #manual-help').hide();
        $('#auto-help').show();
        $('#auto-field').val('1');
    });
    $('#manual').click(function(e){
        $('.manual-fields, #manual-help').show();
        $('#auto-help').hide();
        $('#auto-field').val('0');
    });
    </script>
    <style>.manual-fields, #manual-help {display: none;}</style>

evewspace/POS/templates/edit_pos.html
<div title="Edit Starbase" id="editPOSDialog" class="addPOSDialog">
    <div class="modal-header">
        <div class="row">
            <div class="span6">
                <h4>Edit POS</h4>
            </div>
            <div class="span3 offset2">
                <a href="#" class="btn" onclick="$('#modalHolder').modal('hide');">Cancel</a>
                <a href="#" class="btn btn-primary" id="btnEditPOS">Save POS</a>
           </div>
        </div>
    </div>
    <div class="modal-body">
         <div class="alert alert-error" id="pos_message" style="display: none;">
            <p id="pos_error"></p>
         </div>
   <form id="editPOSForm" action="/pos/{{system.pk}}/{{pos.id}}/edit/" method="POST">
        {% csrf_token %}
        Full Corp Name: <input id="corpBox" class="corpAuto" value="{{pos.corporation.name}}" name="corp" type="text" > <br />
        <span class="label label-warning" id="digiterror">Please enter digits only for planet and moon. </span><br /><br />
        Planet: <input name="planet" value="{{pos.planet}}" class="input-mini" type="text"> 
        Moon: <input name="moon" value="{{pos.moon}}"class="input-mini" type="text"> <br />
        Tower Name: <input name="name" value="{{pos.posname}}" type="text"> <br />
        Tower Type: <input id="towertype" class="towerAuto" value="{{pos.towertype.name}}" name="tower" type="text"> <br />
        Status: <br />
        <input type="radio" onclick="Test(this);" name="status" value="0" {% if pos.status == 0 %}checked="checked" {% endif %}> &nbsp Unanchored<br />
        <input type="radio" name="status" onclick="Test(this);" value="1"{% if pos.status == 1 %}checked="checked" {% endif %}> &nbsp Anchored <br />
        <input type="radio" name="status" onclick="Test(this);" value="2"{% if pos.status == 2 %}checked="checked" {% endif %}> &nbsp Onlining<br />
        <input type="radio" name="status" onclick="Test(this);" value="3"{% if pos.status == 3 %}checked="checked" {% endif %}> &nbsp Reinforced<br />
        <input type="radio" name="status" value="4" onclick="Test(this);" {% if pos.status == 4 %}checked="checked" {% endif %}> &nbsp Online <br />
        <br />
        <div id="rftime" class="rftimerdiv" style="display: none">
            RF Timer: Days: <input name="rfdays" class="input-mini" type="text">
            Hours: <input name="rfhours" class="input-mini" type="text">
            Minutes: <input name="rfminutes" class="input-mini" type="text">
        </div>
        Fitting: <br />
        <textarea  rows="10" name="fitting">{{fitting}}</textarea><br />
        Parse as D-Scan Paste: <input type="checkbox" name="dscan" value="1"> <br />
    </form>
    </div>
    <div class="modal-footer">
    </div>
    <script type="text/javascript">
    function Test(rad){
        var rads=document.getElementsByName(rad.name);
        document.getElementById('rftime').style.display=(rads[3].checked)?'block':'none';
    }
    $('#editPOSForm').submit(function(e){
                e.preventDefault();
                EditPOS({{pos.pk}}, {{system.pk}});
                $('#modalHolder').modal('hide');
                return false;
                });
    $('#btnEditPOS').click(function(e){
                EditPOS({{pos.pk}}, {{system.pk}});
                $('#modalHolder').modal('hide');
                });
    </script>
</div>

evewspace/POS/templates/posdetails_small.html
<li id="pos{{pos.pk}}" class="posListItem">
{% if perms.POS.change_pos %}
<i class="icon-pencil" onclick="GetEditPOSDialog({{pos.pk}}, {{system.pk}});" title="Edit POS"></i>
{% endif %}
{% if perms.POS.delete_pos %}
<i class="icon-ban-circle" onclick="DeletePOS({{pos.pk}}, {{system.pk}});" title="Delete POS"></i>
{% endif %}

<div class="poslist_header" data-toggle="collapse" data-target="#pos{{pos.pk}}Details" style="position:relative">
        <i class="icon-chevron-down" style="cursor: pointer;" title="Click to expand / collapse"></i> <img height="48" width="48" src="http://image.eveonline.com/Render/{{pos.towertype.pk}}_128.png"></img>
        <span class="planetlabel">Planet: </span>
        <span class="planetno"><strong>{{pos.planet}}</strong></span>
		<span class="moonlabel">Moon: </span>
        <span class="moonno"><strong>{{pos.moon}}<strong></span>&nbsp
        <span class="posname"><strong>{{pos.posname}}</strong></span>&nbsp &nbsp
        <br />
        <div class="posSummary">
            <span class="postype"><strong>{{pos.towertype.name}}</strong></span><br />
            {% if pos.status == 0 %}
                <span class="label label-info">Status: UNANCHORED</span>
            {% endif %}
            {% if pos.status == 1 %}
                <span class="label label-info">Status: ANCHORED</span>
            {% endif %}
            {% if pos.status == 2 %}
                <span class="label label-info">Status: ONLINING</span>
            {% endif %}
            {% if pos.status == 3 %}
                <span class="label label-important">Status: REINFORCED  Comes Out: {{pos.rftime|date:"Y-m-d H:i"}}</span>
            {% endif %}
            {% if pos.status == 4 %}
                <span class="label label-success">Status: ONLINE</span>
            {% endif %}
                <br />
            {% if pos.guns %}
                <img height="32" width="32" title="GUNS" src="/static/images/posguns.png" /> {{pos.guns}}
            {% endif %}
            {% if pos.ewar %}
                <img height="32" width="32" title="EWAR" src="/static/images/posewar.png" /> {{pos.ewar}}
            {% endif %}
            {% if pos.sma %}
                <img height="32" width="32" title="SMA" src="/static/images/possma.png" /> {{pos.sma}}
            {% endif %}
            {% if pos.hardener %}
                <img height="32" width="32" title="HARDENERS" src="/static/images/poshard.png" /> {{pos.hardener}}
            {% endif %}
            <br />
            Updated: {{pos.updated|date:"Y-m-d H:i"}}
            {% if pos.warpin_notice %}
                <br />
                <span title="Warp-in Notice" class="label label-warning">{{pos.warpin_notice}}</span>
            {% endif %}
        </div>
	</div>
    <div id="pos{{pos.pk}}Details" class="poslist_main collapse">
        <div class="poslist_info">
            <h5>Owner: </h5>
            <img src="http://image.eveonline.com/Corporation/{{pos.corporation.id}}_32.png" ></img> &nbsp
            {% if pos.corporation.alliance %}
            <img src="http://image.eveonline.com/Alliance/{{pos.corporation.alliance.id}}_32.png"></img>
            {% endif %}
            <br />
            <span class="poslist_corplabel">Corp: </span>
			<a href="http://www.zkillboard.com/corporation/{{pos.corporation.id}}/" target="_blank" class="killboard_link">{{pos.corporation.name}}</a>
            <span class="poslist_ticker">[{{pos.corporation.ticker}}]</span><br />
            {% if pos.corporation.alliance %}
            <span class="poslist_alliancelable">Alliance: </span>
            <a href="http://www.zkillboard.com/alliance/{{pos.corporation.alliance.id}}/" target="_blank" class="killboard_link">{{pos.corporation.alliance.name}}</a>
            <span class="poslist_ticker">[{{pos.corporation.alliance.shortname}}]</span><br />
            {% endif %}
            <span class="poslist_posname">Name: {{pos.posname}}</span> <br />
            <h5>Full Fitting: </h5>
            <span class="poslist_fitting">{{pos.fitting|linebreaksbr}}</span> <br />
		</div>
	</div>
</li>